<?php

namespace Exceedone\Exment\Enums;

class Timezone extends EnumBase
{
    /**
     * TIMEZONE LIST
     * *Please replace "_" to "/"!!
     */
    public const TIMEZONE = [
        'Pacific_Midway'       => "(GMT-11:00) Midway Island",
        'US_Samoa'             => "(GMT-11:00) Samoa",
        'US_Hawaii'            => "(GMT-10:00) Hawaii",
        'US_Alaska'            => "(GMT-09:00) Alaska",
        'US_Pacific'           => "(GMT-08:00) Pacific Time (US &amp; Canada)",
        'America_Tijuana'      => "(GMT-08:00) Tijuana",
        'US_Arizona'           => "(GMT-07:00) Arizona",
        'US_Mountain'          => "(GMT-07:00) Mountain Time (US &amp; Canada)",
        'America_Chihuahua'    => "(GMT-07:00) Chihuahua",
        'America_Mazatlan'     => "(GMT-07:00) Mazatlan",
        'America_Mexico_City'  => "(GMT-06:00) Mexico City",
        'America_Monterrey'    => "(GMT-06:00) Monterrey",
        'Canada_Saskatchewan'  => "(GMT-06:00) Saskatchewan",
        'US_Central'           => "(GMT-06:00) Central Time (US &amp; Canada)",
        'US_Eastern'           => "(GMT-05:00) Eastern Time (US &amp; Canada)",
        'US_East-Indiana'      => "(GMT-05:00) Indiana (East)",
        'America_Bogota'       => "(GMT-05:00) Bogota",
        'America_Lima'         => "(GMT-05:00) Lima",
        'America_Caracas'      => "(GMT-04:30) Caracas",
        'Canada_Atlantic'      => "(GMT-04:00) Atlantic Time (Canada)",
        'America_La_Paz'       => "(GMT-04:00) La Paz",
        'America_Santiago'     => "(GMT-04:00) Santiago",
        'Canada_Newfoundland'  => "(GMT-03:30) Newfoundland",
        'America_Buenos_Aires' => "(GMT-03:00) Buenos Aires",
        'Greenland'            => "(GMT-03:00) Greenland",
        'Atlantic_Stanley'     => "(GMT-02:00) Stanley",
        'Atlantic_Azores'      => "(GMT-01:00) Azores",
        'Atlantic_Cape_Verde'  => "(GMT-01:00) Cape Verde Is.",
        'Africa_Casablanca'    => "(GMT) Casablanca",
        'Europe_Dublin'        => "(GMT) Dublin",
        'Europe_Lisbon'        => "(GMT) Lisbon",
        'Europe_London'        => "(GMT) London",
        'Africa_Monrovia'      => "(GMT) Monrovia",
        'Europe_Amsterdam'     => "(GMT+01:00) Amsterdam",
        'Europe_Belgrade'      => "(GMT+01:00) Belgrade",
        'Europe_Berlin'        => "(GMT+01:00) Berlin",
        'Europe_Bratislava'    => "(GMT+01:00) Bratislava",
        'Europe_Brussels'      => "(GMT+01:00) Brussels",
        'Europe_Budapest'      => "(GMT+01:00) Budapest",
        'Europe_Copenhagen'    => "(GMT+01:00) Copenhagen",
        'Europe_Ljubljana'     => "(GMT+01:00) Ljubljana",
        'Europe_Madrid'        => "(GMT+01:00) Madrid",
        'Europe_Paris'         => "(GMT+01:00) Paris",
        'Europe_Prague'        => "(GMT+01:00) Prague",
        'Europe_Rome'          => "(GMT+01:00) Rome",
        'Europe_Sarajevo'      => "(GMT+01:00) Sarajevo",
        'Europe_Skopje'        => "(GMT+01:00) Skopje",
        'Europe_Stockholm'     => "(GMT+01:00) Stockholm",
        'Europe_Vienna'        => "(GMT+01:00) Vienna",
        'Europe_Warsaw'        => "(GMT+01:00) Warsaw",
        'Europe_Zagreb'        => "(GMT+01:00) Zagreb",
        'Europe_Athens'        => "(GMT+02:00) Athens",
        'Europe_Bucharest'     => "(GMT+02:00) Bucharest",
        'Africa_Cairo'         => "(GMT+02:00) Cairo",
        'Africa_Harare'        => "(GMT+02:00) Harare",
        'Europe_Helsinki'      => "(GMT+02:00) Helsinki",
        'Europe_Istanbul'      => "(GMT+02:00) Istanbul",
        'Asia_Jerusalem'       => "(GMT+02:00) Jerusalem",
        'Europe_Kiev'          => "(GMT+02:00) Kyiv",
        'Europe_Minsk'         => "(GMT+02:00) Minsk",
        'Europe_Riga'          => "(GMT+02:00) Riga",
        'Europe_Sofia'         => "(GMT+02:00) Sofia",
        'Europe_Tallinn'       => "(GMT+02:00) Tallinn",
        'Europe_Vilnius'       => "(GMT+02:00) Vilnius",
        'Asia_Baghdad'         => "(GMT+03:00) Baghdad",
        'Asia_Kuwait'          => "(GMT+03:00) Kuwait",
        'Africa_Nairobi'       => "(GMT+03:00) Nairobi",
        'Asia_Riyadh'          => "(GMT+03:00) Riyadh",
        'Europe_Moscow'        => "(GMT+03:00) Moscow",
        'Asia_Tehran'          => "(GMT+03:30) Tehran",
        'Asia_Baku'            => "(GMT+04:00) Baku",
        'Europe_Volgograd'     => "(GMT+04:00) Volgograd",
        'Asia_Muscat'          => "(GMT+04:00) Muscat",
        'Asia_Tbilisi'         => "(GMT+04:00) Tbilisi",
        'Asia_Yerevan'         => "(GMT+04:00) Yerevan",
        'Asia_Kabul'           => "(GMT+04:30) Kabul",
        'Asia_Karachi'         => "(GMT+05:00) Karachi",
        'Asia_Tashkent'        => "(GMT+05:00) Tashkent",
        'Asia_Kolkata'         => "(GMT+05:30) Kolkata",
        'Asia_Kathmandu'       => "(GMT+05:45) Kathmandu",
        'Asia_Yekaterinburg'   => "(GMT+06:00) Ekaterinburg",
        'Asia_Almaty'          => "(GMT+06:00) Almaty",
        'Asia_Dhaka'           => "(GMT+06:00) Dhaka",
        'Asia_Novosibirsk'     => "(GMT+07:00) Novosibirsk",
        'Asia_Bangkok'         => "(GMT+07:00) Bangkok",
        'Asia_Jakarta'         => "(GMT+07:00) Jakarta",
        'Asia_Krasnoyarsk'     => "(GMT+08:00) Krasnoyarsk",
        'Asia_Chongqing'       => "(GMT+08:00) Chongqing",
        'Asia_Hong_Kong'       => "(GMT+08:00) Hong Kong",
        'Asia_Kuala_Lumpur'    => "(GMT+08:00) Kuala Lumpur",
        'Australia_Perth'      => "(GMT+08:00) Perth",
        'Asia_Singapore'       => "(GMT+08:00) Singapore",
        'Asia_Taipei'          => "(GMT+08:00) Taipei",
        'Asia_Ulaanbaatar'     => "(GMT+08:00) Ulaan Bataar",
        'Asia_Urumqi'          => "(GMT+08:00) Urumqi",
        'Asia_Irkutsk'         => "(GMT+09:00) Irkutsk",
        'Asia_Seoul'           => "(GMT+09:00) Seoul",
        'Asia_Tokyo'           => "(GMT+09:00) 日本",
        'Australia_Adelaide'   => "(GMT+09:30) Adelaide",
        'Australia_Darwin'     => "(GMT+09:30) Darwin",
        'Asia_Yakutsk'         => "(GMT+10:00) Yakutsk",
        'Australia_Brisbane'   => "(GMT+10:00) Brisbane",
        'Australia_Canberra'   => "(GMT+10:00) Canberra",
        'Pacific_Guam'         => "(GMT+10:00) Guam",
        'Australia_Hobart'     => "(GMT+10:00) Hobart",
        'Australia_Melbourne'  => "(GMT+10:00) Melbourne",
        'Pacific_Port_Moresby' => "(GMT+10:00) Port Moresby",
        'Australia_Sydney'     => "(GMT+10:00) Sydney",
        'Asia_Vladivostok'     => "(GMT+11:00) Vladivostok",
        'Asia_Magadan'         => "(GMT+12:00) Magadan",
        'Pacific_Auckland'     => "(GMT+12:00) Auckland",
        'Pacific_Fiji'         => "(GMT+12:00) Fiji",
    ];
}
