name: php-cs-fixer

on:
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ "8.0", "8.1" ]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Prepare
        run: |
          wget https://cs.symfony.com/download/php-cs-fixer-v3.phar -O php-cs-fixer
          chmod a+x php-cs-fixer

      - name: Versions
        run: |
          cat /etc/os-release
          php -v
          php php-cs-fixer --version

      - name: Execute php-cs-fixer
        run: |
          php php-cs-fixer fix --dry-run -v --diff ./src
          php php-cs-fixer fix --dry-run -v --diff ./tests
